### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AnandBaburajan** [Kukkee/Kukkee#118]
We've our docs hosted at https://rocketmeet.gitbook.io/rocketmeet/ which is common for all three of our repos. It's empty at the moment. We also don't have much to put there. We can get started however, with the content from our readme.

**Comment by RituCs** [comment]
I would like to work on this issue.

**Comment by AnandBaburajan** [comment]
Thanks @RituCs! Though we're happy to see you're interested, we would suggest you to take up a bit more challenging issues which would help you learn more. You're always welcome to ask doubts - so feel free too! Let us know which issue you pick or if you want suggestions.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.

**Comment by AnandBaburajan** [comment]
Thanks for showing interest @AshuKV! But I'd like to suggest you to take up a bit more challenging issues.

**Comment by AnandBaburajan** [comment]
Closing this since we can use GitHub's wikis.
