### ISSUE TITLE
Readme: Misleading instructions for .env.production

### ISSUE THREAD

**Issue by AnandBaburajan** [Kukkee/Kukkee#121]
In our readme, it's mentioned to create both .env.production and .env.development in the **Setup** section, which is incorrect. They should be in the **Development** and **Deployment** sections respectively, Also, 'development' should be 'production' [here](https://github.com/RocketMeet/RocketMeet-client/blob/main/.env.production.example#L15).

Edit: also in the **Setup** section, it's mentioned to "Set the encryption variables and domain URLs in the .env files", which needs to be fixed similarly. The "Set firebase config variables in .env files." needs to be fixed too.

**Comment by himanshu007-creator** [comment]
HI, i would like to work on this issue. Please assign me this issue.

**Comment by AnandBaburajan** [comment]
Hi @himanshu007-creator? Thanks for showing interest! Can you share what made you interested in this issue?

**Comment by himanshu007-creator** [comment]
> Hi @himanshu007-creator! Thanks for showing interest! Can you share what made you interested in this issue?

its the <code>gssoc</code> label sir,

**Comment by AnandBaburajan** [comment]
> > Hi @himanshu007-creator! Thanks for showing interest! Can you share what made you interested in this issue?
> 
> its the `gssoc` label sir,

Oh, okay. We would appreciate it if you check out our project and find an issue which interests you. Feel free to let us know if you've any doubts! Looking forward to your response!

**Comment by AnandBaburajan** [comment]
We need to mention that there should be a single firebase project associated with all the services. Maybe also mention that the email encryption key and iv need to be the same for all services.

**Comment by AnandBaburajan** [comment]
Closing this since we're rewriting the entire readme.
