### ISSUE TITLE
'If need be' option

### ISSUE THREAD

**Issue by AnandBaburajan** [Kukkee/Kukkee#122]
Users can be provided a 'If need be' option to vote time slots which are okay-ish but aren't ideal.

**Comment by BreadGenie** [comment]
Can you explain a bit more about it?
Is it like allowing the voters to select the time slots that are beyond what the creator have made? 🤔

**Comment by AnandBaburajan** [comment]
> Is it like allowing the voters to select the time slots that are beyond what the creator have made?

Nope. Currently voters mark their options which are best for them. The "if need be" votes would be a "second priority" kind of vote which are like "hey, I don't like these slots as much as my first priority slots, but if there's need, I'm okay with these". The "need" here could be helpful, for example, in the situation when no one's first priority options have an intersection. In that case, the poll creator would be able to consider people's "if need be" votes. Doodle has this option too, and one can try it out there.

**Comment by BreadGenie** [comment]
Tried it out and it looks like a nice feature to have.
This would require PRs on both repos right?

**Comment by AnandBaburajan** [comment]
> This would require PRs on both repos right?

Yep.
