### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by letslunchpool** [Kukkee/Kukkee#138]
**Describe the bug**
npm run build fails

```
Failed to compile.

./src/styles/global.css
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: pages\_app.tsx


> Build error occurred
Error: > Build failed because of webpack errors
    at C:\Users\AlexanderAbell\OneDrive - Lunchpool\Documents\GitHub\RocketMeet-client\node_modules\next\dist\build\index.js:397:19
    at async Span.traceAsyncFn (C:\Users\AlexanderAbell\OneDrive - Lunchpool\Documents\GitHub\RocketMeet-client\node_modules\next\dist\telemetry\trace\trace.js:60:20)
    at async Object.build [as default] (C:\Users\AlexanderAbell\OneDrive - Lunchpool\Documents\GitHub\RocketMeet-client\node_modules\next\dist\build\index.js:77:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rocketmeet-client@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rocketmeet-client@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AlexanderAbell\AppData\Roaming\npm-cache\_logs\2021-12-22T05_01_57_563Z-debug.log
```

**To Reproduce**
1. Upgrade react to 16.14.0 
2. 'npm run build' in command line after cloning

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by AnandBaburajan** [comment]
Thank you @letslunchpool for reporting this! We'll look into this.

> Hi! I'm looking to see about integrating this as a lunch/coffee scheduling tool for my company Lunchpool

I got an email about your message, but I'm not able to access our chatroom on Gitter because of a 500 error so I'll address it here. First of all, I'm happy to see that you're interested in RocketMeet! I would be more happy to discuss and figure out how RocketMeet can integrate with your product. Can you please share an overview of how you think the integration would look like?

**Comment by letslunchpool** [comment]
Hi Anand! Might be easier to walk through on a 5-10min call? I tried installing a local version but got stuck in the documentation. Is the email service depracated? Are you guys still actively developing RocketMeet?

Thanks,
Alex


[https://lh4.googleusercontent.com/UibCwKyRwqlAr_fhaS7F19L1wBIqzzuSn7W6OyzyG-iXpoGvYNvKoxqHB0zfuNAVamTOEg3F-tifOkS4xad1eT40yYAk4pgm7zquTaiAhAziC_EEgIJurGmXOsqxBDotaXyMchkH]

[https://lh4.googleusercontent.com/b1-qbGwwxEYJJLQCS81_aL_EoUW7TMoLtAe7rzWgYKhvYC1klpGJjulRVpcG4wvvwtt2f_cQYLiOx5S0yuMgFehHPGb0cJs5BPdsN9gFU5RFeYAZwfiC5n_xLSHQs-jYBl_oHQHW]

Alexander Abell

Founder, CEO & Lunch Break Enforcer

Lunchpool<https://lunchpool.io/>


***@***.******@***.***>

(813) 534-3383


[Facebook]<https://facebook.com/letslunchpool>[LinkedIn]<https://linkedin.com/company/letslunchpool>[Instagram]<https://www.instagram.com/letslunchpool/>

________________________________

**Comment by AnandBaburajan** [comment]
> Hi Anand! Might be easier to walk through on a 5-10min call?

Sure, can you pick a slot from https://rocketmeet.me/poll/61c463401f55950004e634d0? If none of the slots work, can you please create a new poll with your availability and share it here?

> I tried installing a local version but got stuck in the documentation.

Ah.

> Is the email service depracated?

Yep.

> Are you guys still actively developing RocketMeet?

We put the development on hold for a while but will be continue developing next month onwards. It's still in its initial stages and hasn't been launched yet, so your feedback would be very helpful.

**Comment by AnandBaburajan** [comment]
Hello @letslunchpool. We've fixed this issue and revamped the project. Please check it out and let us know your thoughts! : )
