### ISSUE TITLE
“redux-persist failed to create sync storage. falling back to noop storage.”

### ISSUE THREAD

**Issue by anaswaratrajan** [Kukkee/Kukkee#64]
On `development`, getting the warning
```
“redux-persist failed to create sync storage. falling back to noop storage.”
```

**Comment by anaswaratrajan** [comment]
https://github.com/rt2zz/redux-persist/issues/1208 It's an open issue from `redux-persist`. Issue doesn't seem to affect the functionality of the app.

**Comment by ponikar** [comment]
@manishprivet You can use Redux with NextJs. 
Things get a little bit tricky when SSR
But we have the library called next-redux-wrapper. It has done this SSR store job amazingly,
Check it out.

**Comment by AnandBaburajan** [comment]
Closing this since we aren't using Redux anymore.
