### ISSUE TITLE
Comma-separation handler on poll pages not working on mobile

### ISSUE THREAD

**Issue by AnandBaburajan** [Kukkee/Kukkee#78]
From reports by different users, it looks like it could be a browser-related issue too.

**Comment by anaswaratrajan** [comment]
Currently email tags are formed only if comma-delimited. Forming tags for more keypress events like tab, space and enter could prove user-friendly and intuitive. @VipinVIP @AnandBaburajan What do you think?

**Comment by namansamra** [comment]
@AnandBaburajan  I would like to implement this keypress functionality . Could you assign it to me?

**Comment by AnandBaburajan** [comment]
Closing this since we don't have this feature anymore. We can open it again later if/when we face it again.
